source "https://rubygems.org"

ruby "3.2.1"

gem "rails", "~> 7.1.3", ">= 7.1.3.2"


gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem 'config'

gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem 'state_machines-activerecord'
gem "bootsnap", require: false
gem 'slim-rails'

# auth
gem 'devise'
gem 'omniauth-keycloak'
gem 'omniauth-rails_csrf_protection'
gem 'rolify'
gem 'cancancan'

# http
gem 'faraday'
gem 'httplog'


group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

gem "karafka", ">= 2.3.0"
