default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ates_task_tracker_development
  username: postgres
  password: postgres
  host: localhost
  port: 5433

test:
  <<: *default
  database: ates_task_tracker_development_test

