keycloak:
  url: 'http://keycloak:8080'
  auth_url: 'http://localhost:7000'
  realm: 'master'
  client_id: 'task_tracker'
  credentials:
    username: 'admin'
    password: 'admin'

root_url: "http://task_tracker:9000"