default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ates_analytics_development
  username: postgres
  password: postgres
  host: postgres
  port: 5432

test:
  <<: *default
  database: ates_analytics_development_test

